### ISSUE TITLE
Use CircleCI for continuous integration

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hydra-editor#167]
Derived from samvera/maintenance#16

**Comment by jrgriffiniii** [comment]
This is only blocked by a consistently failing test:

```
1) routes to the records controller ids with percent routes them
     Failure/Error: let(:audio) { Audio.new(id: id) }
     Ldp::BadRequest:
     # ./spec/routing/records_routing_spec.rb:6:in `new'
     # ./spec/routing/records_routing_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/routing/records_routing_spec.rb:8:in `block (2 levels) in <top (required)>'
```

within `rspec ./spec/routing/records_routing_spec.rb:22 # routes to the records controller ids with percent routes them`

**Comment by jrgriffiniii** [comment]
This completes for me locally without breaking, I'll proceed by inspecting the difference in FCRepo versions deployed locally and using the Docker Container on CircleCI.
